apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: locations
  name: locations
  namespace: services
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: locations
  template:
    metadata:
      labels:
        app: locations
    spec:
      containers:
      - name: locations
        image: us.gcr.io/new-eden-storage-a5c23/chingy-locations:v1.45
        env:
          - name: EVE_CLIENT_ID
            value: "e996e0b1bc8049368ce06873775cb4f1"
          - name: EVE_SECRET
            value: "W6JrAgvpgQGt3hWOs0sPdIm8idv6Ade3UWSwzSAO"

