apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: locations
  name: locations
  namespace: services
spec:
  selector:
    matchLabels:
      run: locations
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: locations
    spec:
      containers:
      - name: locations
        image: us.gcr.io/new-eden-storage-a5c23/chingy-locations:v1.16
        ports:
        - containerPort: 8000
          protocol: TCP